version: "3.8"

services:
  products-service:
    build:
      context: ./products-service
    container_name: products-service
    ports:
      - "${PRODUCTS_PORT}:3000"
    environment:
      - PORT=3000
      - INTERNAL_API_KEY=${INTERNAL_API_KEY_PRODUCTS}
    networks:
      - app-network

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "${INVENTORY_PORT}:3001"
    environment:
      - PORT=3001
      - INTERNAL_API_KEY=${INTERNAL_API_KEY_INVENTORY}
      - PRODUCTS_SERVICE_API_KEY=${PRODUCTS_SERVICE_API_KEY}
      - PRODUCTS_SERVICE_BASE_URL=${PRODUCTS_SERVICE_BASE_URL}
    depends_on:
      - products-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
